### ISSUE TITLE
No implicit conversion of nil into String

### ISSUE THREAD

**Issue by Hey-Feres** [skryukov/inertia_rails-contrib#12]
When I run ``bin/rails generate inertia:install`` I got the error below:

```bash
/Users/brunoferesvillela/.gem/ruby/2.7.2/gems/inertia_rails-contrib-0.2.0/lib/generators/inertia/install/install_generator.rb:63:in `read': no implicit conversion of nil into String (TypeError)
```

I'm following the instructions from [this link](https://inertia-rails.netlify.app/guide/server-side-setup.html).

My ruby version is `2.7.2` and rails version is `6.1.7.3`.

Any help on how to solve this will be useful!!

Here's the full output:

```bash
➜  my_app git:(main) ✗ bin/rails generate inertia:install
Installing Inertia's Rails adapter
Could not find a Vite configuration files (`config/vite.json` & `vite.config.{ts,js,mjs,cjs}`).  
Would you like to install Vite Ruby? (y/n) y
         run  bundle add vite_rails from "."
Vite Rails gem successfully installed
         run  bundle exec vite install from "."
Vite Rails successfully installed
Would you like to install Tailwind CSS? (y/n) n
Adding Inertia's Rails adapter initializer
      create  config/initializers/inertia_rails.rb
Installing Inertia npm packages
What framework do you want to use with Inertia? [react, vue, svelte] (react) react
         run  yarn add @inertiajs/react react react-dom @vitejs/plugin-react --silent from "."
warning " > @vitejs/plugin-react@4.3.1" has unmet peer dependency "vite@^4.2.0 || ^5.0.0".
[#########################################################################################################################################] 1217/1217
Traceback (most recent call last):
	21: from bin/rails:5:in `<main>'
	20: from /Users/brunoferesvillela/.gem/ruby/2.7.2/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	19: from /Users/brunoferesvillela/.gem/ruby/2.7.2/gems/bootsnap-1.15.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	18: from /Users/brunoferesvillela/.gem/ruby/2.7.2/gems/railties-6.1.7.3/lib/rails/commands.rb:18:in `<main>'
	17: from /Users/brunoferesvillela/.gem/ruby/2.7.2/gems/railties-6.1.7.3/lib/rails/command.rb:48:in `invoke'
	16: from /Users/brunoferesvillela/.gem/ruby/2.7.2/gems/railties-6.1.7.3/lib/rails/command/base.rb:69:in `perform'
	15: from /Users/brunoferesvillela/.gem/ruby/2.7.2/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	14: from /Users/brunoferesvillela/.gem/ruby/2.7.2/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	13: from /Users/brunoferesvillela/.gem/ruby/2.7.2/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	12: from /Users/brunoferesvillela/.gem/ruby/2.7.2/gems/railties-6.1.7.3/lib/rails/commands/generate/generate_command.rb:26:in `perform'
	11: from /Users/brunoferesvillela/.gem/ruby/2.7.2/gems/railties-6.1.7.3/lib/rails/generators.rb:275:in `invoke'
	10: from /Users/brunoferesvillela/.gem/ruby/2.7.2/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	 9: from /Users/brunoferesvillela/.gem/ruby/2.7.2/gems/thor-1.2.1/lib/thor/group.rb:232:in `dispatch'
	 8: from /Users/brunoferesvillela/.gem/ruby/2.7.2/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `invoke_all'
	 7: from /Users/brunoferesvillela/.gem/ruby/2.7.2/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `map'
	 6: from /Users/brunoferesvillela/.gem/ruby/2.7.2/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `each'
	 5: from /Users/brunoferesvillela/.gem/ruby/2.7.2/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `block in invoke_all'
	 4: from /Users/brunoferesvillela/.gem/ruby/2.7.2/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	 3: from /Users/brunoferesvillela/.gem/ruby/2.7.2/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	 2: from /Users/brunoferesvillela/.gem/ruby/2.7.2/gems/inertia_rails-contrib-0.2.0/lib/generators/inertia/install/install_generator.rb:43:in `install'
	 1: from /Users/brunoferesvillela/.gem/ruby/2.7.2/gems/inertia_rails-contrib-0.2.0/lib/generators/inertia/install/install_generator.rb:63:in `install_inertia'
/Users/brunoferesvillela/.gem/ruby/2.7.2/gems/inertia_rails-contrib-0.2.0/lib/generators/inertia/install/install_generator.rb:63:in `read': no implicit conversion of nil into String (TypeError)
```

**Comment by skryukov** [comment]
Could you try running vite rails installation manually:
bundle exec vite install

The generator fails to find vite.config.* and fails (will fix that to show an appropriate message). The question is why vite install haven't generated the config file 🤔

**Comment by Hey-Feres** [comment]
@skryukov running it manually worked!! Thank you.

**Comment by skryukov** [comment]
@Hey-Feres great! I believe you had `webpacker` installed in your app. Is that true?
